name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components and accept licenses
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses

      # Compila il progetto che sta nella cartella EquiConti/
      - name: Build Release APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: EquiConti
          arguments: assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: EquiConti-APK
          path: EquiConti/app/build/outputs/apk/release/app-release.apk
